#!/usr/bin/env python

import os
from admin_api.crypt import Keypair

exepath = os.path.dirname(os.path.realpath(__file__))
cnfgfile = '%s/%s' % (exepath, 'serverkeys.cfg')

mykeypair = Keypair(cnfgfile=cnfgfile, keyname='serverkeys')
data = mykeypair.encrypt('Hello There')
print 'The decrypted string is %s' % (mykeypair.decrypt(data))

